version: '3.9'

services:
  storage-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storage-db
    ports:
      - "3306:3306"
    volumes:
      - storage-db-data:/var/lib/mysql
    networks:
      - resource-network
volumes:
  storage-db-data:
    driver: local
networks:
  resource-network:
    external:
      name: resource-network
