server:
  port: 8084

spring:
  application:
    name: storage-serve
  profiles:
    default: dev
  datasource:
    url: jdbc:mysql://localhost:3306/storage-db?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect