server:
  port: 8084
spring:
  application:
    name: storage-service
  profiles:
    default: dev
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOSTNAME}:8090/
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME}:3306/${DB_NAME}?serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${SECURITY_HOSTNAME}:8088
logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
management:
  endpoints:
    web:
      exposure:
        include: '*'
