spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storage-db?serverTimezone=UTC
    username: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088
local:
  configuration:
    cors: false
